version: "3.9"
services:
    web:
        build:
            context: app
        image: phpweb
        network_mode: host
        ports:
            - 80:80
        volumes:
            - ./app/src:/var/www/html/
    db:
        build:
            context: db
        image: mssqldb
        network_mode: host
        ports:
            - 1433:1433
        healthcheck:
            test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Un!q@to2023 -Q 'SELECT 1' || exit 1"]
            interval: 10s
            retries: 10
            start_period: 10s
            timeout: 3s
        volumes:
            - ./data:/var/opt/mssql/data